In [7]:
import numpy as np
from simenvs.hcwsim import HCWSim

# Dynamics
Initialize the HCW Dynamics

In [6]:
sim = HCWSim()
# print("A\n",sim.A)
# print("B\n",sim.B)
# print("C\n",sim.C)
# print("D\n",sim.D)

HCW Sim initialized
A
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e-02
   1.12762156e-07  0.00000000e+00]
 [-1.43379977e-15  1.00000000e+00  0.00000000e+00 -1.12762156e-07
   1.00000000e-02  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e-02]
 [ 3.81458616e-08  0.00000000e+00  0.00000000e+00  1.00000000e+00
   2.25524165e-05  0.00000000e+00]
 [-4.30140959e-13  0.00000000e+00  0.00000000e+00 -2.25524165e-05
   1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.27152872e-08  0.00000000e+00
   0.00000000e+00  1.00000000e+00]]
B
 [[ 2.50000163e-05  1.87936478e-10  0.00000000e+00]
 [-1.87936478e-10  2.50000650e-05  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.50000163e-05]
 [ 5.00000000e-03  2.81905389e-08  0.00000000e+00]
 [-5.63810778e-08  5.00000000e-03  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  5.00000000e-03]]
C
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
D
 [[0. 0. 0.]
 [0. 

# Stability
Check the eigenvalues of (A-BK)

In [ ]:
# evals = np.linalg.eig(sim.A - sim.B.dot(K))